language: ruby
rvm:
  - 2.0.0
env:
  - DB=sqlite
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace 
  - RAILS_ENV=test rspec spec
